apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubescape
  namespace: security-audit
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kubescape
        spec:
          containers:
          - name: kubescape
            image: quay.io/kubescape/kubescape:latest
            # Pasamos los parámetros como "args" en lugar de "command"
            # Esto respeta el ejecutable interno de la imagen oficial
            args: 
            - "scan"
            - "framework"
            - "nsa"
            env:
            - name: KUBESCAPE_HOME
              value: /tmp/.kubescape
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 10001
              capabilities:
                drop:
                  - ALL
            volumeMounts:
            - name: cache-volume
              mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
          - name: cache-volume
            emptyDir: {}