apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-sa
  namespace: security-audit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescape-readonly-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "configmaps", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io", "cilium.io"]
  resources: ["networkpolicies", "ciliumnetworkpolicies", "ciliumclusterwidenetworkpolicies"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubescape-readonly-binding
subjects:
- kind: ServiceAccount
  name: kubescape-sa
  namespace: security-audit
roleRef:
  kind: ClusterRole
  name: kubescape-readonly-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubescape
  namespace: security-audit
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kubescape
        spec:
          # Le asignamos la nueva identidad con permisos de lectura
          serviceAccountName: kubescape-sa
          containers:
          - name: kubescape
            image: quay.io/kubescape/kubescape-cli:latest
            command: ["kubescape"]
            args: 
            - "scan"
            - "framework"
            - "nsa"
            env:
            - name: KUBESCAPE_HOME
              value: /tmp/.kubescape
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 10001
              capabilities:
                drop:
                  - ALL
            volumeMounts:
            - name: cache-volume
              mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
          - name: cache-volume
            emptyDir: {}